### ISSUE TITLE
Problema de sc

### ISSUE THREAD

**Issue by ArthurBetaTester** [Andrews571/Winoptimize#1]
![Captura de tela 2024-04-03 224526](https://github.com/Andrews571/AGOptimizer/assets/165973559/bc17358f-dba0-497e-ab69-ec317c33439d)
### _****_
![Captura de tela 2024-04-03 224511](https://github.com/Andrews571/AGOptimizer/assets/165973559/4874f693-206e-4dbe-82d7-9c5acb0ecfa9)

Erro Sc

**Comment by Andrews571** [comment]
This error occurs because administrator privileges are not activated. (run as administrator)

**Comment by Andrews571** [comment]
Fix in new update, but execute with administrator privileges...
